image: patrickmckernin/msmqueries22winter

tasks:
  - before: |
      cp -r /base-rails/gems/ruby vendor/bundle
      bundle config set --local path 'vendor/bundle'
      rails db:create db:migrate
      rails db:seed
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9500-9999
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
